// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import path from "node:path";
import { configDotenv } from "dotenv";
import { defineConfig } from "prisma/config";

const nodeEnv = process.env.NODE_ENV ?? "development";
const envPath = path.join(import.meta.dirname, `.env.${nodeEnv}`);

configDotenv({
	path: envPath,
});

export default defineConfig({
	schema: "src/prisma/schema.prisma",
	migrations: {
		path: "src/prisma/migrations",
	},
	datasource: {
		url: process.env.DATABASE_URL,
	},
});
